#!/usr/bin/env bash

echo "Installing xorg..."
sudo apt install xorg -y

echo "Installing printer system"
sudo apt install cups -y

echo "Installing scanner driver and software..."
sudo apt install libsane \  #SANE (Scanner Access Now Easy) for Debian (https://wiki.debian.org/Scanner)
  brscan4  \ # Brother scanner driver
  gscan2pdf # Scanner software
sudo brsaneconfig4 -a name=Scanner model=HLL2380DW ip=192.168.88.238 #Setup network scanner


