#!/usr/bin/env bash

## Setup Home Folders
[ ! -d ~/Documents ] && mkdir Documents
[ ! -d ~/Downloads ] && mkdir Downloads
[ ! -d ~/Git ] && mkdir Git

# Add multimedia repositories
dpkg-query -l | grep -q deb-multimedia-keyring || \
	wget -P ~/Downloads https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb \
	|| sudo apt install ~/Downloads/deb-multimedia-keyring_2016.8.1_all.deb
[ ! -f /etc/apt/sources.list.d/multimedia.list || sudo wget -P /etc/apt/sources.list.d https://raw.githubusercontent.com/ChevySSinSD/debian-i3-gaps-dotfiles/t430-debian-i3-gaps/etc/apt/sources.list.d/multimedia.list
sudo apt update && sudo apt upgrade && sudo apt autoremove

# Download and install Bluetooth Firmware
dpkg-query -l | grep -q broadcom-bt-firmware || \
	wget  -P ~/Downloads https://github.com/winterheart/broadcom-bt-firmware/releases/download/v12.0.1.1105_p3/broadcom-bt-firmware-10.1.0.1115.deb \
	|| sudo apt install ~/Downloads/broadcom-bt-firmware-10.1.0.1115.deb

# Install Git
sudo apt install git
git config --global user.name "Eric Roeder"
git config --global user.email eric.roeder@gmail.com

# Install i3 Gaps (if not already installed)
dpkg-query -l | grep -q gerardo || git clone https://github.com/maestrogerardo/i3-gaps-deb.git ~/Git/i3-gaps-deb || sh ~/Git/i3-gaps-deb/i3-gaps-deb

# Install apt packages
sudo apt install xorg `#			Xorg` \
	pulseaudio pavucontrol `# 		Audio and volume control` \
	xfce4-power-manager `# 			Power Manager` \
	cups `#					Printer support` \
	libsane brscan4 gscan2pdf `#		Scanner support: SANE, Brother Scanner Drivers, and scanner software` \
	rclone `#				Google Drive support` \
	libreoffice libreoffice-gtk3 `#		Libreoffice` \
	neofetch htop `#			Command line utilities` \
	ranger `#				Ranger - command line file manager` \
	fonts-roboto `#				Roboto fonts` \
	mpv `#					MPV video player`

# Set up network scanner
sudo brsaneconfig4 -a name=Scanner model=HLL2380DW ip=192.168.88.238 #Setup network scanner

# Install Google Chrome
dpkg-query -l | grep -q google-chrome-stable || wget -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb || sudo apt install ~/Downloads/google-chrome-stable_current_amd64.deb

#Install LibreOffice numbertext extension
[ ! -f ~/Downloads/numbertext-1-0-5.oxt ] && wget -P ~/Downloads https://extensions.libreoffice.org/assets/downloads/z/numbertext-1-0-5.oxt
sudo /usr/lib/libreoffice/program/unopkg add ~/Downloads/numbertext-1-0-5.oxt --shared -s -f

# Install Powerline Fonts
git clone https://github.com/powerline/fonts.git ~/Git/powerline
sh ~/Git/powerline/install.sh

# Clean Up
sudo rm -R ~/Git/powerline
sudo apt upgrade -y
sudo apt autoremove -y
