#!/usr/bin/env bash

# Setup Folders
[ ! -d ~/Documents ] && mkdir Documents
[ ! -d ~/Downloads ] && mkdir Downloads
[ ! -d ~/Git ] && mkdir Git
[ ! -d ~/.local/bin ] && mkdir ~/.local/bin
[ ! -d ~/scripts ] && mkdir  ~/scripts
[ ! -d ~/scripts/rofi ] && mkdir  ~/scripts/rofi
[ ! -d ~/scripts/bash ] && mkdir  ~/scripts/bash

# Add multimedia repositories
dpkg-query -l | grep -q deb-multimedia-keyring || \
	wget -P ~/Downloads https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb \
	|| sudo apt install ~/Downloads/deb-multimedia-keyring_2016.8.1_all.deb
[ ! -f /etc/apt/sources.list.d/multimedia.list ] && \
	sudo wget -P /etc/apt/sources.list.d https://raw.githubusercontent.com/ChevySSinSD/debian-i3-gaps-dotfiles/t430-debian-i3-gaps/etc/apt/sources.list.d/multimedia.list
sudo apt update && sudo apt upgrade && sudo apt autoremove

# Download and install Bluetooth Firmware
dpkg-query -l | grep -q broadcom-bt-firmware || \
	wget -P ~/Downloads https://github.com/winterheart/broadcom-bt-firmware/releases/latest/download/broadcom-bt-firmware-10.1.0.1115.deb \
	|| sudo apt install ~/Downloads/broadcom-bt-firmware-10.1.0.1115.deb

# Disable Bluetooth SAP plugin (eliminate bluetooth errors on boot)
[ ! -f /etc/systemd/system/bluetooth.service.d/override.conf ] && \
	sudo wget -P /etc/systemd/system/bluetooth.service.d https://raw.githubusercontent.com/ChevySSinSD/debian-i3-gaps-dotfiles/t430-debian-i3-gaps/etc/systemd/system/bluetooth.service.d/override.conf

# Install Git
sudo apt install git
git config --global user.name "Eric Roeder"
git config --global user.email eric.roeder@gmail.com

# Install i3 Gaps (if not already installed)
dpkg-query -l | grep -q gerardo || git clone https://github.com/maestrogerardo/i3-gaps-deb.git ~/Git/i3-gaps-deb || sh ~/Git/i3-gaps-deb/i3-gaps-deb

# Apt packages - Install
#	xorg					X display server
#	xss-lock numlockx			X tools for locking screen and activating numlock
#	network-manager				NetworkManager for WiFi and ethernet
#	gir1.2-nm-1.0				Required for NetworkManager_dmenu
#	autorandr				Tool for automatic monitor switching
#	dex					.Desktop file tool
#	feh					Image viewer used for desktop background
#	gimp					Raster image software
#	inkscape				Vector image software
#	pulseaudio pavucontrol	 		Audio and volume control
#	xfce4-power-manager 			Power Manager
#	cups					Printer support
#	libsane brscan4 gscan2pdf		Scanner support: SANE, Brother Scanner Drivers, and scanner software
#	rclone					Google Drive support
#	libreoffice libreoffice-gtk3		Libreoffice with GTK3 theme support
#	neofetch				System info tool
#	htop					System process monitor tool
#	ranger					Command line file manager
# 	lxappearance				GTK theme manager
#	mpv					Media player
#	python3-pip				Python package manager
#	rofi					Program Launcher (dmenu replacement)
#	polybar					Bar (i3bar replacement)
#	calc					Requried for random color support

sudo apt install xorg xss-lock numlockx network-manager gir1.2-nm-1.0 autorandr dex \
	feh gimp inkscape pulseaudio pavucontrol xfce4-power-manager cups libsane brscan4 gscan2pdf \
	rclone libreoffice libreoffice-gtk3 neofetch htop ranger lxappearance mpv python3-pip rofi polybar calc

# Apt packages - Remove
#	Xorg intel drivers 	- using default modesetting drivers instead
#	i3bar			- using polybar instead
sudo apt remove xserver-xorg-video-intel i3bar

# Install pywal (Automatically set colors based on wallpaper)
sudo pip3 install pywal

# Install Networkmanager-dmenu
[ ! -f ~/.local/bin/networkmanager_dmenu ] && wget -P ~/Downloads https://github.com/firecat53/networkmanager-dmenu/archive/refs/tags/v2.1.0.tar.gz \
	&& tar -xvf ~/Downloads/v2.1.0.tar.gz --strip-components=1 --directory ~/Downloads/ \
	&& cp ~/Downloads/networkmanager_dmenu ~/.local/bin/ \
	&& cp ~/Downloads/networkmanager_dmenu.desktop ~/.local/share/applications/

# Install acpilight (xbacklight replacement that works with modesetting driver)
git clone https://gitlab.com/wavexx/acpilight.git ~/Git/acpilight
sudo make -C ~/Git/acpilight/ install

# Remove i3bar
sudo apt remove i3bar

# Set up network scanner
sudo brsaneconfig4 -a name=Scanner model=HLL2380DW ip=192.168.88.238 #Setup network scanner

# Install Google Chrome
dpkg-query -l | grep -q google-chrome-stable || wget -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb || sudo apt install ~/Downloads/google-chrome-stable_current_amd64.deb

# Install LibreOffice numbertext extension
[ ! -f ~/Downloads/numbertext-1-0-5.oxt ] && wget -P ~/Downloads https://extensions.libreoffice.org/assets/downloads/z/numbertext-1-0-5.oxt
sudo /usr/lib/libreoffice/program/unopkg add ~/Downloads/numbertext-1-0-5.oxt --shared -s -f

# Install Spotifyd
[ ! -f ~/.local/bin/spotifyd ] && wget -P ~/Downloads https://github.com/Spotifyd/spotifyd/releases/latest/download/spotifyd-linux-full.tar.gz \
	&& tar -xf ~/Downloads/spotifyd-linux-full.tar.gz --directory ~/.local/bin

# Install Spotify TUI
[ ! -f ~/.local/bin/spt ] && wget -P ~/Downloads https://github.com/Rigellute/spotify-tui/releases/latest/download/spotify-tui-linux.tar.gz \
	&& tar -xf ~/Downloads/spotify-tui-linux.tar.gz --directory ~/.local/bin

# Install Powerline Font Patches
git clone https://github.com/powerline/fonts.git ~/Git/powerline
sh ~/Git/powerline/install.sh

# Install Hack Font with Nerd Patch (for Polybar)
wget -P ~/Downloads https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip
unzip -qj ~/Downloads/Hack.zip -d ~/.local/share/fonts/
sudo fc-cache ~/.local/share/fonts -f

# Install Play with MPV
pip install git+https://github.com/thann/play-with-mpv --user

# Install yt-dlp and remove youtube-dl
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
pip uninstall youtube-dl

# Install powerline scripts
wget -P ~/scripts/bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
git clone https://github.com/magicmonty/bash-git-prompt.git ~/scripts/bash/bash-git-prompt --depth=1
wget -P ~/scripts/bash/bash-git-prompt/themes https://raw.githubusercontent.com/lucascosti/bashrc/fb3ce2b0c2193d27c20a6c4cb64bb443506c5849/bashscripts/bash-git-prompt/themes/Lucas_bullettrain_tags.bgptheme

# Install my dotfiles

# Clean Up
rm -R ~/Git/*
rm ~/Downloads/*

# Reboot the system
sudo reboot
