#!/usr/bin/env bash

# Setup Folders
[ ! -d ~/Documents ] && mkdir ~/Documents
[ ! -d ~/Downloads ] && mkdir ~/Downloads
[ ! -d ~/Git ] && mkdir ~/Git
[ ! -d ~/.local/bin ] && mkdir ~/.local/bin
[ ! -d ~/scripts ] && mkdir  ~/scripts
[ ! -d ~/scripts/rofi ] && mkdir  ~/scripts/rofi
[ ! -d ~/scripts/bash ] && mkdir  ~/scripts/bash

# Install Git
sudo apt install git 
git config --global user.name "ChevySSinSD"
git config --global user.email eric.roeder@gmail.com

# Install GitHub CLI
wget -O- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt update && sudo apt install gh

# Setup SSH
ssh-keygen -t ed25519 -C "eric.roeder@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
gh auth login

# Install my dotfiles from github
echo ".cfg" >> $HOME/.gitignore
git clone --bare git@github.com:ChevySSinSD/debian-i3-gaps-dotfiles.git $HOME/.cfg
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
mkdir -p .config-backup && \
	config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
	xargs -I{} mv {} .config-backup/{}
config checkout
config config --local status.showUntrackedFiles no
config fetch origin

# Add Multimedia Repository keyrings
wget -N -P ~/Downloads https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
sudo apt install ~/Downloads/deb-multimedia-keyring_2016.8.1_all.deb

# Copy etc files from repository to correct location
#	/etc/sudoers.d/eric (enable power down without sudo password)
#	/etc/systemd/system/bluetooth.service.d/override.conf (disable bluetooth SAP)
#	/etc/apt/sources.list.d/ (Testing & Unstable Source and Multimedia repositories)
sudo cp -a --no-preserve=all -v ~/etc /
sudo apt update && sudo apt upgrade && sudo apt autoremove

# Download and install Bluetooth Firmware
wget -N -P ~/Downloads https://github.com/winterheart/broadcom-bt-firmware/releases/latest/download/broadcom-bt-firmware-10.1.0.1115.deb
sudo apt install ~/Downloads/broadcom-bt-firmware-10.1.0.1115.deb

# Apt packages - Install
#	xorg					X display server
#	xss-lock numlockx i3lock-fancy		X tools for locking screen and activating numlock
#	network-manager				NetworkManager for WiFi and ethernet
#	gir1.2-nm-1.0				Required for NetworkManager_dmenu
#	autorandr				Tool for automatic monitor switching
#	dex					.Desktop file tool
#	feh					Image viewer used for desktop background
#	gimp					Raster image software
#	inkscape				Vector image software
#	pulseaudio pavucontrol	 		Audio and volume control
#	xfce4-power-manager 			Power Manager
#	cups					Printer support
#	libsane gscan2pdf			Scanner support: SANE, and scanner software
#	rclone					Google Drive support
#	libreoffice libreoffice-gtk3		Libreoffice with GTK3 theme support
#	neofetch				System info tool
#	htop					System process monitor tool
#	ranger					Command line file manager
#	thunar					GUI file manager
# 	lxappearance				GTK theme manager
#	mpv					Media player
#	python3-pip				Python package manager
#	rofi					Program Launcher (dmenu replacement)
#	polybar					Bar (i3bar replacement)
#	calc					Requried for random color support
#	playerctl				command-line utility and library for controlling media players that implement the MPRIS D-Bus Interface Specification
#	papirus-icon-theme			Papirus Icon Theme

sudo apt update && sudo apt upgrade && sudo apt autoremove
sudo apt install xorg xss-lock numlockx network-manager gir1.2-nm-1.0 autorandr dex \
	feh gimp inkscape pulseaudio pavucontrol xfce4-power-manager cups libsane gscan2pdf \
	rclone libreoffice libreoffice-gtk3 neofetch htop ranger thunar lxappearance mpv \
	python3-pip rofi polybar calc playerctl papirus-icon-theme

# Install i3 Gaps
git clone https://github.com/maestrogerardo/i3-gaps-deb.git ~/Git/i3-gaps-deb
(cd ~/Git/i3-gaps-deb ; ./i3-gaps-deb)

# Apt packages - Remove
#	xserver-xorg-video-intel		use modesetting driver instead
#	i3status				using polybar instead
sudo apt remove xserver-xorg-video-intel i3status

# Install picom
git clone https://github.com/ibhagwan/picom.git ~/Git/picom
sudo apt install libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre2-dev libpcre3-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev meson libx11-xcb-dev libxcb-sync-dev cmake libxcb-composite0-dev libxcb-present-dev xcb libxcb-glx0-dev uthash-dev libconfig-dev libgl-dev libdbus-1-dev
(cd ~/Git/picom ; git submodule update --init --recursive ; meson --buildtype=release . build ; sudo ninja -C build install)

# Install Networkmanager-dmenu and remove previous manual config
wget -N -P ~/Downloads https://github.com/firecat53/networkmanager-dmenu/archive/refs/tags/v2.1.0.tar.gz
tar -xvf ~/Downloads/v2.1.0.tar.gz --strip-components=1 --directory ~/Downloads/
cp ~/Downloads/networkmanager_dmenu ~/.local/bin/
cp ~/Downloads/networkmanager_dmenu.desktop ~/.local/share/applications/
sudo rm /etc/network/interfaces.d/wifi

# Install acpilight (xbacklight replacement that works with modesetting driver)
git clone https://gitlab.com/wavexx/acpilight.git ~/Git/acpilight
sudo make -C ~/Git/acpilight/ install

# Install brother scanner driver
wget -N -P ~/Downloads https://download.brother.com/welcome/dlf105200/brscan4-0.4.11-1.amd64.deb
sudo apt install ~/Downloads/brscan4-0.4.11-1.amd64.deb

# Set up scanner
sudo brsaneconfig4 -a name=Scanner model=HLL2380DW ip=192.168.88.238 #Setup network scanner

# Install Google Chrome
wget -N -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ~/Downloads/google-chrome-stable_current_amd64.deb

# Install LibreOffice numbertext extension
wget -N -P ~/Downloads https://extensions.libreoffice.org/assets/downloads/z/numbertext-1-0-5.oxt
sudo /usr/lib/libreoffice/program/unopkg add ~/Downloads/numbertext-1-0-5.oxt --shared -s -f

# Install LibreOffice icon theme
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-libreoffice-theme/master/install-papirus-root.sh | sh

# Install Spotifyd
wget -N -P ~/Downloads https://github.com/Spotifyd/spotifyd/releases/latest/download/spotifyd-linux-full.tar.gz
tar -xf ~/Downloads/spotifyd-linux-full.tar.gz --directory ~/.local/bin

# Install Spotify TUI
wget -N -P ~/Downloads https://github.com/Rigellute/spotify-tui/releases/latest/download/spotify-tui-linux.tar.gz
tar -xf ~/Downloads/spotify-tui-linux.tar.gz --directory ~/.local/bin

# Install RobotoMono Hack Font (for Polybar, Rofi, and XResources)
wget -N -P ~/Downloads https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/RobotoMono.zip
unzip -qj ~/Downloads/RobotoMono.zip -d ~/.local/share/fonts/
fc-cache -f -v

# Install Play with MPV
pip install git+https://github.com/thann/play-with-mpv --user

# Install yt-dlp and remove youtube-dl
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
pip uninstall youtube-dl

# Install powerline scripts
wget -N -P ~/scripts/bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
git clone https://github.com/magicmonty/bash-git-prompt.git ~/scripts/bash/bash-git-prompt --depth=1
wget -N -P ~/scripts/bash/bash-git-prompt/themes https://raw.githubusercontent.com/lucascosti/bashrc/fb3ce2b0c2193d27c20a6c4cb64bb443506c5849/bashscripts/bash-git-prompt/themes/Lucas_bullettrain_tags.bgptheme

# Install GTK theme
wget -N -P ~/Downloads https://github.com/EliverLara/Sweet/releases/latest/download/Sweet-Dark.zip
sudo unzip ~/Downloads/Sweet-Dark.zip -d /usr/share/themes/

# Install zscroll for spotify polybar module
git clone https://github.com/noctuid/zscroll ~/Git/zscroll
(cd ~/Git/zscroll ; sudo python3 setup.py install)

# Apt cleanup
sudo apt update && sudo apt upgrade && sudo apt autoremove

# Reboot the system
sudo reboot
